title: "Blog de Psicologia e Neurociencias"
description: "Artigos cientificos sobre psicologia, neurociencias e ciencia aberta em portugues"
lang: pt-BR
baseurl: "/science-blog-por"
url: "https://juanmoisesd.github.io"

theme: minima

author:
  name: "Juan Moises de la Serna"

show_excerpts: true

minima:
  skin: classic

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Juan Moises de la Serna"
